#Accepting input through stdin
all: ; g++ repstring.cpp -o repstring -Wall

#Running test cases for the program
test: ; g++ repstring.cpp -DTEST -o repstring -Wall

#Removing the binary
clean: ; rm repstring
